'------------------------------------------------------------------------------
' <autogenerated>
'	 This code was generated by a tool.
'	 Runtime Version: 1.1.4322.573
'
'	 Changes to this file may cause incorrect behavior and will be lost if 
'	 the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

' 
' This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
' 

Imports Microsoft.VisualBasic
	Imports System.Diagnostics
	Imports System.Xml.Serialization
	Imports System
	Imports System.Web.Services.Protocols
	Imports System.ComponentModel
	Imports System.Web.Services
Namespace Chapter26_WebClient.SoapSecurity


	''' <remarks/>
	<System.Diagnostics.DebuggerStepThroughAttribute(), System.ComponentModel.DesignerCategoryAttribute("code"), System.Web.Services.WebServiceBindingAttribute(Name:="SoapSecurityServiceSoap", Namespace:="http://tempuri.org/")> _
	Public Class SoapSecurityService : Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

		Public TicketHeaderValue As TicketHeader

		''' <remarks/>
		Public Sub New()
			Me.Url = "http://localhost/Chapter26/SoapSecurityService.asmx"
		End Sub

		''' <remarks/>
		<System.Web.Services.Protocols.SoapHeaderAttribute("TicketHeaderValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
		Public Sub Login(ByVal userName As String, ByVal password As String, ByVal hashAlgorithm As HashAlgorithm)
			Me.Invoke("Login", New Object() { userName, password, hashAlgorithm})
		End Sub

		''' <remarks/>
		Public Function BeginLogin(ByVal userName As String, ByVal password As String, ByVal hashAlgorithm As HashAlgorithm, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
			Return Me.BeginInvoke("Login", New Object() { userName, password, hashAlgorithm}, callback, asyncState)
		End Function

		''' <remarks/>
		Public Sub EndLogin(ByVal asyncResult As System.IAsyncResult)
			Me.EndInvoke(asyncResult)
		End Sub

		''' <remarks/>
		<System.Web.Services.Protocols.SoapHeaderAttribute("TicketHeaderValue"), System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEmployees", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
		Public Function GetEmployees() As System.Data.DataSet
			Dim results As Object() = Me.Invoke("GetEmployees", New Object(){})
			Return (CType(results(0), System.Data.DataSet))
		End Function

		''' <remarks/>
		Public Function BeginGetEmployees(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
			Return Me.BeginInvoke("GetEmployees", New Object(){}, callback, asyncState)
		End Function

		''' <remarks/>
		Public Function EndGetEmployees(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
			Dim results As Object() = Me.EndInvoke(asyncResult)
			Return (CType(results(0), System.Data.DataSet))
		End Function
	End Class

	''' <remarks/>
	<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://tempuri.org/"), System.Xml.Serialization.XmlRootAttribute(Namespace:="http://tempuri.org/", IsNullable:=False)> _
	Public Class TicketHeader : Inherits System.Web.Services.Protocols.SoapHeader

		''' <remarks/>
		Public Ticket As String
	End Class

	''' <remarks/>
	<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://tempuri.org/")> _
	Public Enum HashAlgorithm

		''' <remarks/>
		''' <remarks/>
		''' <remarks/>
		SHA1
		MD5
		Clear
		
	End Enum
End Namespace
