'------------------------------------------------------------------------------
' <autogenerated>
'	 This code was generated by a tool.
'	 Runtime Version: 1.1.4322.573
'
'	 Changes to this file may cause incorrect behavior and will be lost if 
'	 the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

' 
' This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
' 

Imports Microsoft.VisualBasic
	Imports System.Diagnostics
	Imports System.Xml.Serialization
	Imports System
	Imports System.Web.Services.Protocols
	Imports System.ComponentModel
	Imports System.Web.Services
Namespace WebClient.localhost


	''' <remarks/>
	<System.Diagnostics.DebuggerStepThroughAttribute(), System.ComponentModel.DesignerCategoryAttribute("code"), System.Web.Services.WebServiceBindingAttribute(Name:="Employees ServiceSoap", Namespace:="http://www.apress.com/ProASP.NET/")> _
	Public Class EmployeesService : Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

		''' <remarks/>
		Public Sub New()
			Dim urlSetting As String = System.Configuration.ConfigurationSettings.AppSettings("WebClient.localhost.Employees Service")
			If (Not urlSetting Is Nothing) Then
				Me.Url = String.Concat(urlSetting, "")
			Else
				Me.Url = "http://localhost/Chapter24/EmployeesService.asmx"
			End If
		End Sub

		''' <remarks/>
		<System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.apress.com/ProASP.NET/GetEmployeesCount", RequestNamespace:="http://www.apress.com/ProASP.NET/", ResponseNamespace:="http://www.apress.com/ProASP.NET/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
		Public Function GetEmployeesCount() As Integer
			Dim results As Object() = Me.Invoke("GetEmployeesCount", New Object(){})
			Return (CInt(results(0)))
		End Function

		''' <remarks/>
		Public Function BeginGetEmployeesCount(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
			Return Me.BeginInvoke("GetEmployeesCount", New Object(){}, callback, asyncState)
		End Function

		''' <remarks/>
		Public Function EndGetEmployeesCount(ByVal asyncResult As System.IAsyncResult) As Integer
			Dim results As Object() = Me.EndInvoke(asyncResult)
			Return (CInt(results(0)))
		End Function

		''' <remarks/>
		<System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.apress.com/ProASP.NET/GetEmployees", RequestNamespace:="http://www.apress.com/ProASP.NET/", ResponseNamespace:="http://www.apress.com/ProASP.NET/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
		Public Function GetEmployees() As System.Data.DataSet
			Dim results As Object() = Me.Invoke("GetEmployees", New Object(){})
			Return (CType(results(0), System.Data.DataSet))
		End Function

		''' <remarks/>
		Public Function BeginGetEmployees(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
			Return Me.BeginInvoke("GetEmployees", New Object(){}, callback, asyncState)
		End Function

		''' <remarks/>
		Public Function EndGetEmployees(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
			Dim results As Object() = Me.EndInvoke(asyncResult)
			Return (CType(results(0), System.Data.DataSet))
		End Function
	End Class
End Namespace
